name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.0, 3.1, 3.2]
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "Ruby tests: version ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.version }}
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run rspec
        run: bundle exec rspec
