name: CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [2.7, 3.0, 3.1, 3.2]
    steps:
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
          with:
            bundler-cache: true
            ruby-version: ${{matrix.version}}
      - name: run RSpec
        run: bundle exec rspec
